/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nl.koop.overheid.movetocds;

import java.nio.file.Path;
import java.nio.file.Paths;

import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.DefaultParser;
import org.apache.commons.cli.HelpFormatter;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.ParseException;

public class App {
    public boolean moveToCDS(String zipPayloadPath, String oin, String idLevering, String verzoekFase) {
        MoveToCDS cds = new MoveToCDS();
        Path zipPayload = Paths.get(zipPayloadPath);
        return cds.process(zipPayload, oin, idLevering, verzoekFase);
    }

    public static void main(String[] args) {
        Options options = new Options();

        Option optInput = new Option("z", "zip", true, "zip payload locatie");
        optInput.setRequired(true);
        options.addOption(optInput);
        Option optOin = new Option("o", "oin", true, "identificatie Aanleveraar");
        optOin.setRequired(true);
        options.addOption(optOin);
        Option optIdLevering = new Option("i", "idlevering", true, "identificatie Levering");
        optIdLevering.setRequired(true);
        options.addOption(optIdLevering);

        CommandLineParser parser = new DefaultParser();
        HelpFormatter formatter = new HelpFormatter();
        CommandLine cmd = null;//not a good practice, it serves it purpose 

        try {
            cmd = parser.parse(options, args);
        } catch (ParseException e) {
            System.out.println(e.getMessage());
            formatter.printHelp("MoveToCDS", options);

            System.exit(1);
        }
        String zipPayloadPath = cmd.getOptionValue("zip");
        String oin = cmd.getOptionValue("oin");
        String idLevering = cmd.getOptionValue("idlevering");

        System.out.println("zipPayloadPath=" + zipPayloadPath);
        System.out.println("oin=" + oin);
        System.out.println("idlevering=" + idLevering);
        new App().moveToCDS(zipPayloadPath, oin, idLevering, "validatie");
    }
}
